# Generated by Django 5.0.2 on 2024-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebasemodel',
            old_name='name',
            new_name='password',
        ),
        migrations.AddField(
            model_name='firebasemodel',
            name='username',
            field=models.CharField(default='default_user', max_length=255),
            preserve_default=False,
        ),
    ]
