# Generated by Django 5.0.2 on 2024-02-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_firebasemodel_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasemodel',
            name='email',
            field=models.EmailField(default='default_user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firebasemodel',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
